info:
    app:
        name: catalog-pdf-generator-service
        description: Generates PDF files from items in the catalog

server:
  port: 8020

byggmester-bob:
    pageUrlTemplate: http://www.nb.no/services/image/resolver?url_ver=Z39.88-2004&rft_id={urn}&svc_id=info:lanl-repo/svc/getRegion&svc_val_fmt=info:ofi/fmt:kev:mtx:jpeg2000&svc.format={format}&svc.level={svc.level}&svc.rotate=0&action=pdf
