info:
    app:
        name: catalog-pdf-generator-service
        description: Generates PDF files from items in the catalog
    build:
        artifact: ${project.artifactId}
        name: ${project.name}
        description: ${project.description}
        version: ${project.version}

endpoints:
  restart:
    enabled: true
  refresh:
    enabled: true

server:
  port: 8070

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    
byggmester-bob:
    pageUrlTemplate: http://www.nb.no/services/image/resolver?url_ver=Z39.88-2004&rft_id={urn}&svc_id=info:lanl-repo/svc/getRegion&svc_val_fmt=info:ofi/fmt:kev:mtx:jpeg2000&svc.format=image/jpeg&svc.level={svc.level}&svc.rotate=0&action=pdf

---
spring:
    profiles: dev

byggmester-bob:
    tilemapUrlTemplate: http://www.nb.no/services/tilesv2/tilemap?URN={urn}&format=json
    altoUrlTemplate: http://appserv3.nb.no:8088/postman-pat/file/{urn}/alto/{urn}.xml

---
spring:
    profiles: prod

byggmester-bob:
    tilemapUrlTemplate: http://localhost:8100/tilesv2/tilemap?URN={urn}&format=json
    altoUrlTemplate: http://localhost:8088/postman-pat/file/{urn}/alto/{urn}.xml

---
spring:
    profiles: integration

byggmester-bob:
    tilemapUrlTemplate: http://www.nb.no/services/tilesv2/tilemap?URN={urn}&format=json
    altoUrlTemplate: http://appserv3.nb.no:8088/postman-pat/file/{urn}/alto/{urn}.xml
